In [1]:
import pandas as pd

In [190]:
che_csv = pd.read_csv('CHE_scrape.csv')
che_json = pd.read_json('CHE_scrape.json')
cleaned_DF = []

In [191]:
for value in che_json['user']:
    normalized = pd.json_normalize(value)
    cleaned_DF.append(normalized)
    
tweets = che_json['full_text'].reset_index(drop=True)
replies = che_json['reply_count'].reset_index(drop=True)
retweets = che_json['retweet_count'].reset_index(drop=True)
favorites = che_json['favorite_count'].reset_index(drop=True)
created = che_json['created_at'].reset_index(drop=True)
url = che_json['url'].reset_index(drop=True)
    

cleaned_DF = pd.concat(cleaned_DF)

# cleaned_DF.merge(tweets, left_on='name', right_on='full_text')

In [170]:
cleaned_DF # all fine here

,id,id_str,name,screen_name,location,description,url,protected,followers_count,fast_followers_count,...,blocking,blocked_by,want_retweets,advertiser_account_type,business_profile_state,translator_type,withheld_in_countries,followed_by,ext_has_nft_avatar,require_some_consent
0,12413032,12413032,The Chronicle of Higher Education,chronicle,"Washington, DC",The leading news source for higher education. ...,https://t.co/6l55jpB6Ju,False,286798,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,12413032,12413032,The Chronicle of Higher Education,chronicle,"Washington, DC",The leading news source for higher education. ...,https://t.co/6l55jpB6Ju,False,286798,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,12413032,12413032,The Chronicle of Higher Education,chronicle,"Washington, DC",The leading news source for higher education. ...,https://t.co/6l55jpB6Ju,False,286798,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,12413032,12413032,The Chronicle of Higher Education,chronicle,"Washington, DC",The leading news source for higher education. ...,https://t.co/6l55jpB6Ju,False,286798,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,12413032,12413032,The Chronicle of Higher Education,chronicle,"Washington, DC",The leading news source for higher education. ...,https://t.co/6l55jpB6Ju,False,286798,0,...,None,None,None,promotable_user,none,none,[],None,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1394545614025904000,1394545614025904130,Belindah,BelindaQini,,Nrm diehard,None,False,335,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,1301170702830252000,1301170702830252035,Jay Dabhi,JayDabh61132607,,Student,None,False,13,0,...,None,None,None,none,none,none,[],None,False,False
0,1295540340837892000,1295540340837892096,Co-Design: Business Education Research Group,CDRG_USYD,University of Sydney Business,Interdisciplinary research group @sydney_uni t...,https://t.co/Qv5Px4P71G,False,318,0,...,None,None,None,promotable_user,none,none,[],None,False,False
0,1357327410946007000,1357327410946007041,Dr Ajanavi Anand,AjanaviDr,,I love my india,None,False,9,0,...,None,None,None,none,none,none,[],None,False,False
0,1488161274424963000,1488161274424963073,Coolermaster,homemadevape,,,None,False,26,0,...,None,None,None,none,none,none,[],None,False,False

In [192]:
# cleaned_DF #concat 'retweet_count', 'full_text', 'reply_count', 'favorite_count', 'created_at', 'url'
# cleaned_DF_1 = cleaned_DF.join(tweets)
# cleaned_DF_2 = cleaned_DF_1.join(replies)
# cleaned_DF_3 = cleaned_DF_2.join(retweets)
# cleaned_DF_4 = cleaned_DF_3.join(favorites)
cleaned_DF = pd.concat([cleaned_DF, created, tweets, replies, retweets, url, favorites])

In [193]:
cleaned_DF

,0,advertiser_account_type,blocked_by,blocking,business_profile_state,can_dm,contributors_enabled,created_at,default_profile_image,description,...,require_some_consent,screen_name,statuses_count,time_zone,translator_type,url,utc_offset,verified,want_retweets,withheld_in_countries
0,NaN,promotable_user,None,None,none,None,False,2008-01-18T20:17:44.000Z,False,The leading news source for higher education. ...,...,False,chronicle,60576.0,None,none,https://t.co/6l55jpB6Ju,None,True,None,[]
0,NaN,promotable_user,None,None,none,None,False,2008-01-18T20:17:44.000Z,False,The leading news source for higher education. ...,...,False,chronicle,60576.0,None,none,https://t.co/6l55jpB6Ju,None,True,None,[]
0,NaN,promotable_user,None,None,none,None,False,2008-01-18T20:17:44.000Z,False,The leading news source for higher education. ...,...,False,chronicle,60576.0,None,none,https://t.co/6l55jpB6Ju,None,True,None,[]
0,NaN,promotable_user,None,None,none,None,False,2008-01-18T20:17:44.000Z,False,The leading news source for higher education. ...,...,False,chronicle,60576.0,None,none,https://t.co/6l55jpB6Ju,None,True,None,[]
0,NaN,promotable_user,None,None,none,None,False,2008-01-18T20:17:44.000Z,False,The leading news source for higher education. ...,...,False,chronicle,60576.0,None,none,https://t.co/6l55jpB6Ju,None,True,None,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [194]:
to_drop = [
'blocked_by',
'blocking',
'business_profile_state',
'can_dm',
'contributors_enabled',
'default_profile_image',
'ext_has_nft_avatar',
'fast_followers_count',
'follow_request_sent',
'followed_by',
'friends_count',
'geo_enabled',
'has_custom_timelines',
'id_str',
'is_translation_enabled',
'is_translator',
'lang',
'listed_count',
'media_count',
'muting',
'normal_followers_count',
'notifications',
'profile_background_color',
'profile_background_image_url',
'profile_background_image_url_https',
'profile_background_tile',
'profile_banner_extensions_sensitive_media_warning',
'profile_banner_url',
'profile_image_extensions_sensitive_media_warning',
'profile_image_url',
'profile_image_url_https',
'profile_sidebar_border_color',
'profile_sidebar_fill_color',
'profile_text_color',
'profile_use_background_image',
'protected',
'require_some_consent',
'retweet_count',
'utc_offset',
'verified',
'want_retweets',
'withheld_in_countries',
'following',
'statuses_count',
'translator_type',
]

In [195]:
for row in cleaned_DF:
    if row in to_drop:
        cleaned_DF.drop(row, axis=1, inplace=True)

In [196]:
cleaned_DF

,0,advertiser_account_type,created_at,description,favourites_count,followers_count,id,location,name,screen_name,time_zone,url
0,NaN,promotable_user,2008-01-18T20:17:44.000Z,The leading news source for higher education. ...,222.0,286798.0,12413032.0,"Washington, DC",The Chronicle of Higher Education,chronicle,None,https://t.co/6l55jpB6Ju
0,NaN,promotable_user,2008-01-18T20:17:44.000Z,The leading news source for higher education. ...,222.0,286798.0,12413032.0,"Washington, DC",The Chronicle of Higher Education,chronicle,None,https://t.co/6l55jpB6Ju
0,NaN,promotable_user,2008-01-18T20:17:44.000Z,The leading news source for higher education. ...,222.0,286798.0,12413032.0,"Washington, DC",The Chronicle of Higher Education,chronicle,None,https://t.co/6l55jpB6Ju
0,NaN,promotable_user,2008-01-18T20:17:44.000Z,The leading news source for higher education. ...,222.0,286798.0,12413032.0,"Washington, DC",The Chronicle of Higher Education,chronicle,None,https://t.co/6l55jpB6Ju
0,NaN,promotable_user,2008-01-18T20:17:44.000Z,The leading news source for higher education. ...,222.0,286798.0,12413032.0,"Washington, DC",The Chronicle of Higher Education,chronicle,None,https://t.co/6l55jpB6Ju
...,...,...,...,...,...,...,...,...,...,...,...,...
495,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
count = 0
for user in cleaned_DF['screen_name']:
    if user == 'chronicle':
        count += 1
print(count)

110